[server]
enableCORS = true
enableXsrfProtection = false
address = "localhost"
port = 8501

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#37474F"
font = "sans serif" 